apiVersion: v1
kind: Service
metadata:
  name: frappe-web
  namespace: kairos
  labels:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: frappe

---
apiVersion: v1
kind: Service
metadata:
  name: frappe-socketio
  namespace: kairos
  labels:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: socketio
spec:
  type: ClusterIP
  ports:
    - name: socketio
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: frappe

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: kairos
  labels:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: redis-cache
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: redis-cache

---
apiVersion: v1
kind: Service
metadata:
  name: redis-queue
  namespace: kairos
  labels:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: redis-queue
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: redis-queue

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: kairos
  labels:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app.kubernetes.io/name: kairos
    app.kubernetes.io/component: database
